# Assignment12 Hoeffding Tree and VFDT

**Importing libraries and dataset**

In [65]:
import numpy as np
import pandas as pd
import time
from itertools import combinations
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.utils import check_array, check_X_y
eps = np.finfo(float).eps
from numpy import log2 as log


In [58]:
df = pd.read_csv('ID3_data.csv')
df

outlook  temp humidity  windy play
0   overcast   hot     high  False  yes
1   overcast  cool   normal   True  yes
2   overcast  mild     high   True  yes
3   overcast   hot   normal  False  yes
4      rainy  mild     high  False  yes
5      rainy  cool   normal  False  yes
6      rainy  cool   normal   True   no
7      rainy  mild   normal  False  yes
8      rainy  mild     high   True   no
9      sunny   hot     high  False   no
10     sunny   hot     high   True   no
11     sunny  mild     high  False   no
12     sunny  cool   normal  False  yes
13     sunny  mild   normal   True  yes

Display informatio about database

In [60]:
data=df.values
print("Type:",type(data))
print("Shape:",data.shape)

rows=data.shape[0]
columns=data.shape[1]
print(columns)
#print(data)

Type: <class 'numpy.ndarray'>
Shape: (14, 5)
5


Find the unique values in each column for the size of Sufficient statistics 

In [63]:
list=df.T.apply(lambda x: x.nunique(), axis=1)
print(list)

m=len(list)
print("Total Columns including dependable features =",m)

# Create 2 dimensional matrix to store the size of i,j,k of the attributes for sufficient statistics
suff_table_size=np.zeros([m-1,3],dtype=int)
#print(suff_table_size)


for i in range(m-1):
    p=list[i]
    suff_table_size[i][0]=i+1
    suff_table_size[i][1]=list[i]
    suff_table_size[i][2]=2
    #print(p)
    #print("List ",list[i])
    
print(suff_table_size)


outlook     3
temp        3
humidity    2
windy       2
play        2
dtype: int64
Total Columns including dependable features = 5
[[1 3 2]
 [2 3 2]
 [3 2 2]
 [4 2 2]]


Define the function to create tree 

In [ ]:
def createTree(df,tree=None): 
    Class = df.keys()[-1]   #To make the code generic, changing target variable class name
    
    #Here we build our decision tree

    #Get attribute with maximum information gain
    node = find_LeafNode(df)
    
    #Get distinct value of that attribute e.g Salary is node and Low,Med and High are values
    attValue = np.unique(df[node])
    
    #Create an empty dictionary to create tree    
    if tree is None:                    
        tree={}
        tree[node] = {}
    
   #We make loop to construct a tree by calling this function recursively. 
    #In this we check if the subset is pure and stops if it is pure. 

    for value in attValue:
        
        subtable = get_subtable(df,node,value)
       # print(subtable)
        clValue,counts = np.unique(subtable[Class],return_counts=True)                        
        
        if len(counts)==1:#Checking purity of subset
            tree[node][value] = clValue[0]                                                    
        else:        
            tree[node][value] = buildTree(subtable) #Calling the function recursively 
                   
    return tree

Define the function to create the leaf node which can be added

In [73]:
# Define the function to create the leaf node and initiallize with various values
def create_LeafNode():
        self.parent = None
        self.left_child = None
        self.right_child = None
        self.split_feature = None
        self.split_value = None  # both continuous and discrete value
        self.new_examples_seen = 0
        self.total_examples_seen = 0
        self.class_frequency = {}
        self.nijk = {f: {} for f in possible_split_features}
        self.possible_split_features = possible_split_features
    


Start iterating over each value for creation of the Tree

In [ ]:
for i in range (rows):
    
    # Sort the vlaues into the leaf l
    a=1
    #iterate over the infinite loop and break it from the body
    while a==1:     
        if self.is_leaf():
            a=2
        else:
            indexnumber = self.possible_split_features.index(self.split_feature)
            value = x[indexnumber]
            split_value = self.split_value
            a=1
    
    #update the nodes 
            